// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web =(
    apiKey: 'AIzaSyC7N1_RaxGFErOtuilloh_EucV__WRjzLg',
    appId: '1:692631829930:web:3ff7f581ef62189735ffd3',
    messagingSenderId: '692631829930',
    projectId: 'authentication-34ad4',
    authDomain: 'authentication-34ad4.firebaseapp.com',
    storageBucket: 'authentication-34ad4.firebasestorage.app',
    measurementId: 'G-LMLRGDE6YQ',
  );

  static FirebaseOptions android =(
    apiKey: 'AIzaSyCECDJgCW8yi5RqZH-3HRN5TdtMHy4kS68',
    appId: '1:692631829930:android:208c5de22211a2c535ffd3',
    messagingSenderId: '692631829930',
    projectId: 'authentication-34ad4',
    storageBucket: 'authentication-34ad4.firebasestorage.app',
  );

  static  FirebaseOptions ios = (
    apiKey: 'AIzaSyCz85HfCezQ85FLhNIeRw8M2toL8QfxnhI',
    appId: '1:692631829930:ios:2214e8ab54c13a0835ffd3',
    messagingSenderId: '692631829930',
    projectId: 'authentication-34ad4',
    storageBucket: 'authentication-34ad4.firebasestorage.app',
    iosBundleId: 'com.example.authtask',
  );

  static FirebaseOptions macos = (
    apiKey: 'AIzaSyCz85HfCezQ85FLhNIeRw8M2toL8QfxnhI',
    appId: '1:692631829930:ios:2214e8ab54c13a0835ffd3',
    messagingSenderId: '692631829930',
    projectId: 'authentication-34ad4',
    storageBucket: 'authentication-34ad4.firebasestorage.app',
    iosBundleId: 'com.example.authtask',
  );

  static FirebaseOptions windows = (
    apiKey: 'AIzaSyC7N1_RaxGFErOtuilloh_EucV__WRjzLg',
    appId: '1:692631829930:web:9fd8bb3f81d968b635ffd3',
    messagingSenderId: '692631829930',
    projectId: 'authentication-34ad4',
    authDomain: 'authentication-34ad4.firebaseapp.com',
    storageBucket: 'authentication-34ad4.firebasestorage.app',
    measurementId: 'G-WFJWMKH0TS',
  );

}